services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    profiles:
      - legacy-traefik
    environment:
      - DOCKER_API_VERSION=1.45
    restart: always
    ports:
      - "80:80"
      - "8443:443"
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt_data:/letsencrypt"
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
    labels:
      - "traefik.enable=true"

  redis:
    image: redis:latest
    container_name: 3xui-shop-redis
    restart: always
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - ./.local/redis-data:/data

  bot:
    build: .
    container_name: 3xui-shop-bot
    network_mode: host
    volumes:
      - ./app/data:/app/data
      - ./plans.json:/app/data/plans.json
      - ./app/locales:/app/locales
      - ./app/logs:/app/logs
    env_file:
      - .env
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6380
      - BOT_PROXY_URL=${BOT_PROXY_URL:-}
    stop_signal: SIGINT
    restart: unless-stopped
    command: sh -c " 
      poetry run pybabel compile -d /app/locales -D bot && 
      poetry run alembic -c /app/db/alembic.ini upgrade head && 
      poetry run python /app/__main__.py"
    depends_on:
      - redis

volumes:
  redis_data:
  letsencrypt_data:
